// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci

// GENERATED by internal/gen from spec/transactions/*.json. Do not edit.

package zbc

const commandsJSON = `[
 {
  "binary": null,
  "body": [
   {
    "encoding": "hex",
    "from": "object_id",
    "name": "object_id",
    "size": 32
   }
  ],
  "command": "accept-dataset",
  "custom": null,
  "description": "Accept a pending dataset transfer.",
  "example": {
   "object_id": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "AcceptDataset",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset object id",
    "kind": "hex32",
    "name": "object_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 44
 },
 {
  "binary": "zbc-storage-prepay",
  "body": [
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "add-prepaid-storage",
  "custom": null,
  "description": "Fund the account's prepaid storage balance (dataset rent).",
  "example": {
   "amount": "100000000"
  },
  "name": "AddPrepaidStorage",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "atomic ZBC",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 9
 },
 {
  "binary": "zbc-app-claim",
  "body": [
   {
    "encoding": "u64le",
    "from": "app_id",
    "name": "app_id"
   }
  ],
  "command": "app-claim",
  "custom": null,
  "description": "Claim the win when an opponent missed the per-move deadline.",
  "example": {
   "app_id": "5"
  },
  "name": "ClaimAppTimeout",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "app id",
    "kind": "int64",
    "name": "app_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 28
 },
 {
  "binary": "zbc-app-create",
  "body": [
   {
    "encoding": "u8",
    "from": "app_type",
    "name": "app_type"
   },
   {
    "encoding": "u64le",
    "from": "stake_token",
    "name": "stake_token"
   },
   {
    "encoding": "u64le",
    "from": "stake_amount",
    "name": "stake_amount"
   },
   {
    "encoding": "u8",
    "from": "seats",
    "name": "seats"
   },
   {
    "encoding": "hex16",
    "from": "params_hex",
    "name": "params_hex"
   },
   {
    "encoding": "hex",
    "from": "opponent_hex",
    "name": "opponent_hex",
    "when": "opponent_hex != ''"
   }
  ],
  "command": "app-create",
  "custom": null,
  "description": "Open an on-chain app (game): type, stake, seats, optional params and opponent.",
  "example": {
   "app_type": "1",
   "opponent_hex": "",
   "params_hex": "",
   "seats": "2",
   "stake_amount": "100000000",
   "stake_token": "0"
  },
  "name": "CreateApp",
  "needs_node": false,
  "notes": [
   "zbc-app-create takes (app_type, stake_token, stake_amount, seats, channel) and cannot pass params or an opponent."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "1 tic-tac-toe, 3 connect-4, 6 gomoku, 16 dice, 17 coin flip",
    "kind": "uint8",
    "name": "app_type",
    "required": true
   },
   {
    "help": "0 = ZBC",
    "kind": "int64",
    "name": "stake_token",
    "required": true
   },
   {
    "help": "stake (atomic)",
    "kind": "int64",
    "name": "stake_amount",
    "required": true
   },
   {
    "default": "2",
    "help": "2 = player vs player, 1 = solo",
    "kind": "uint8",
    "name": "seats",
    "required": false
   },
   {
    "default": "",
    "help": "app parameters (solo bet, e.g. coin flip choice '00')",
    "kind": "hexbytes",
    "name": "params_hex",
    "required": false
   },
   {
    "default": "",
    "help": "36-byte opponent account bytes (open seat if empty); a single byte 01 marks a state-channel app",
    "kind": "hexbytes",
    "name": "opponent_hex",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 24
 },
 {
  "binary": "zbc-app-join",
  "body": [
   {
    "encoding": "u64le",
    "from": "app_id",
    "name": "app_id"
   }
  ],
  "command": "app-join",
  "custom": null,
  "description": "Join an open app seat, locking an equal stake.",
  "example": {
   "app_id": "5"
  },
  "name": "JoinApp",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "app id",
    "kind": "int64",
    "name": "app_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 25
 },
 {
  "binary": "zbc-app-move",
  "body": [
   {
    "encoding": "u64le",
    "from": "app_id",
    "name": "app_id"
   },
   {
    "encoding": "hex16",
    "from": "move_hex",
    "name": "move_hex"
   }
  ],
  "command": "app-move",
  "custom": null,
  "description": "Submit one move.",
  "example": {
   "app_id": "5",
   "move_hex": "04"
  },
  "name": "AppMove",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "app id",
    "kind": "int64",
    "name": "app_id",
    "required": true
   },
   {
    "help": "move bytes, e.g. tic-tac-toe cell 4 = '04'",
    "kind": "hexbytes",
    "name": "move_hex",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 26
 },
 {
  "binary": "zbc-app-resign",
  "body": [
   {
    "encoding": "u64le",
    "from": "app_id",
    "name": "app_id"
   }
  ],
  "command": "app-resign",
  "custom": null,
  "description": "Resign; your stake share goes to the opponent(s).",
  "example": {
   "app_id": "5"
  },
  "name": "ResignApp",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "app id",
    "kind": "int64",
    "name": "app_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 27
 },
 {
  "binary": "zbc-app-settle",
  "body": [
   {
    "encoding": "u64le",
    "from": "app_id",
    "name": "app_id"
   },
   {
    "computed": "number of moves",
    "encoding": "u32le",
    "from": "moves",
    "name": "count"
   },
   {
    "computed": "number of moves",
    "encoding": "u32le",
    "from": "moves",
    "name": "final_seq"
   },
   {
    "computed": "per move: seat u8, move_bytes hex16, 64-byte voucher signature = Ed25519(seat key, SHA3-256(app_id u64le ‖ seq u32le ‖ SHA3-256(9-byte board before the move) ‖ move_bytes)); the board marks cells with seat+1",
    "encoding": "custom",
    "from": "moves",
    "name": "entries"
   }
  ],
  "command": "app-settle",
  "custom": "settle",
  "description": "Settle a two-seat tic-tac-toe state channel: replay the signed moves on chain.",
  "example": {
   "app_id": "5",
   "moves": "0,3,1,4,2",
   "opening_turn": "0",
   "p0_privkey": "1111111111111111111111111111111111111111111111111111111111111111",
   "p1_privkey": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "SettleApp",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the channel app id",
    "kind": "int64",
    "name": "app_id",
    "required": true
   },
   {
    "help": "seat 0 key, signs seat 0 vouchers",
    "kind": "privkey",
    "name": "p0_privkey",
    "required": true
   },
   {
    "help": "seat 1 key",
    "kind": "privkey",
    "name": "p1_privkey",
    "required": true
   },
   {
    "default": "0",
    "help": "seat that moves first, 0 or 1",
    "kind": "uint8",
    "max": 1,
    "min": 0,
    "name": "opening_turn",
    "required": false
   },
   {
    "help": "cells in play order, comma-separated, e.g. 0,3,1,4,2",
    "kind": "string",
    "name": "moves",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 39
 },
 {
  "binary": "zbc-escrow-approve",
  "body": [
   {
    "encoding": "u32le",
    "from": "approval",
    "name": "approval"
   },
   {
    "encoding": "hex",
    "from": "transaction_hash",
    "name": "transaction_hash",
    "size": 32
   }
  ],
  "command": "approve-escrow",
  "custom": null,
  "description": "Approve (0), reject (1) or expire (2) an escrowed transaction, named by its full hash.",
  "example": {
   "approval": "0",
   "transaction_hash": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "ApprovalEscrow",
  "needs_node": false,
  "notes": [
   "The tool reports escrowed_transaction_hash and transaction_id (int64 of the escrowed hash) next to its own transaction_hash."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "0 = approve, 1 = reject, 2 = expire",
    "kind": "uint32",
    "max": 2,
    "min": 0,
    "name": "approval",
    "required": true
   },
   {
    "help": "the escrowed transaction's hash, 64 hex",
    "kind": "hex32",
    "name": "transaction_hash",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 4
 },
 {
  "binary": "zbc-archival-register",
  "body": [
   {
    "encoding": "key32",
    "from": "node_public_key",
    "name": "node_public_key"
   },
   {
    "encoding": "str32",
    "from": "domain",
    "name": "domain"
   },
   {
    "encoding": "str32",
    "from": "url",
    "name": "url"
   }
  ],
  "command": "archival-register",
  "custom": null,
  "description": "Announce a registered node as archival: it serves history and the read API.",
  "example": {
   "domain": "archive.example.org",
   "node_public_key": "2222222222222222222222222222222222222222222222222222222222222222",
   "url": "https://archive.example.org"
  },
  "name": "RegisterArchival",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key (64 hex). Named owner_privkey: ZBC_KEY does not apply, pass it explicitly",
    "kind": "privkey",
    "name": "owner_privkey",
    "required": true
   },
   {
    "help": "the node's ZNK_ address or 64 hex",
    "kind": "key",
    "name": "node_public_key",
    "required": true
   },
   {
    "help": "public domain",
    "kind": "string",
    "name": "domain",
    "required": true
   },
   {
    "help": "public API base URL",
    "kind": "string",
    "name": "url",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "owner_privkey",
  "type": 46
 },
 {
  "binary": "zbc-archival-unregister",
  "body": [
   {
    "encoding": "key32",
    "from": "node_public_key",
    "name": "node_public_key"
   }
  ],
  "command": "archival-unregister",
  "custom": null,
  "description": "Withdraw an archival announcement; the node stays registered.",
  "example": {
   "node_public_key": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "UnregisterArchival",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key (64 hex). Named owner_privkey: ZBC_KEY does not apply, pass it explicitly",
    "kind": "privkey",
    "name": "owner_privkey",
    "required": true
   },
   {
    "help": "the node's ZNK_ address or 64 hex",
    "kind": "key",
    "name": "node_public_key",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "owner_privkey",
  "type": 47
 },
 {
  "binary": "zbc-event-attest",
  "body": [
   {
    "encoding": "str32",
    "from": "event_id",
    "name": "event_id"
   },
   {
    "encoding": "str32",
    "from": "value",
    "name": "value"
   }
  ],
  "command": "attest-event",
  "custom": null,
  "description": "Oracle attestation of an external (event_id, value) by an authorised node account.",
  "example": {
   "event_id": "match-2026-09-16",
   "value": "home"
  },
  "name": "AttestEvent",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "external event id",
    "kind": "string",
    "name": "event_id",
    "required": true
   },
   {
    "help": "attested value",
    "kind": "string",
    "name": "value",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 17
 },
 {
  "binary": "zbc-token-burn",
  "body": [
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "burn-token",
  "custom": null,
  "description": "Burn a token; reclaims backing when redeemable.",
  "example": {
   "amount": "1000",
   "token_id": "123456789"
  },
  "name": "BurnToken",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "token id",
    "kind": "int64",
    "name": "token_id",
    "required": true
   },
   {
    "help": "amount (atomic)",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 13
 },
 {
  "binary": "zbc-cancel-longevity",
  "body": [
   {
    "encoding": "u64le",
    "from": "target_tx_id",
    "name": "target_tx_id"
   }
  ],
  "command": "cancel-longevity",
  "custom": null,
  "description": "Cancel a longevity sponsorship you created; the remainder is refunded.",
  "example": {
   "target_tx_id": "-1234567890123456789"
  },
  "name": "CancelLongevity",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the sponsored transaction's int64 id",
    "kind": "int64",
    "name": "target_tx_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 53
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "u64le",
    "from": "schedule_id",
    "name": "schedule_id"
   }
  ],
  "command": "cancel-schedule",
  "custom": null,
  "description": "Cancel a scheduled transfer (sender) or decline it (recipient).",
  "example": {
   "schedule_id": "11"
  },
  "name": "CancelSchedule",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "schedule id",
    "kind": "int64",
    "name": "schedule_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 30
 },
 {
  "binary": "zbc-trigger-cancel",
  "body": [
   {
    "encoding": "u64le",
    "from": "trigger_id",
    "name": "trigger_id"
   }
  ],
  "command": "cancel-trigger",
  "custom": null,
  "description": "Cancel a pending trigger you own; the locked amount is refunded.",
  "example": {
   "trigger_id": "77"
  },
  "name": "CancelTrigger",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "trigger id",
    "kind": "int64",
    "name": "trigger_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 16
 },
 {
  "binary": "zbc-node-claim",
  "body": [
   {
    "encoding": "pubkey_of_key",
    "from": "node_privkey",
    "name": "node_public_key"
   },
   {
    "computed": "as register-node",
    "encoding": "custom",
    "from": "proof_of_ownership",
    "name": "proof_of_ownership"
   }
  ],
  "command": "claim-node",
  "custom": "proof_of_ownership",
  "description": "Claim the locked balance of a removed or expired node registration.",
  "example": {
   "node_privkey": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "ClaimNodeRegistration",
  "needs_node": true,
  "notes": [
   "zbc-node-claim takes (node_privkey, owner_privkey)."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the node's private key",
    "kind": "privkey",
    "name": "node_privkey",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 770
 },
 {
  "binary": "zbc-trigger-create",
  "body": [
   {
    "encoding": "u64le",
    "from": "fire_height",
    "name": "fire_height"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   },
   {
    "encoding": "str32",
    "from": "event_id",
    "name": "event_id",
    "when": "event_id != ''"
   }
  ],
  "command": "create-trigger",
  "custom": null,
  "description": "Lock amount now and send it to recipient at fire_height, or when an oracle event resolves.",
  "example": {
   "amount": "100000000",
   "event_id": "",
   "fire_height": "100000",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I"
  },
  "name": "CreateTrigger",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "where the scheduled SendZBC pays",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "future block height",
    "kind": "int64",
    "name": "fire_height",
    "required": true
   },
   {
    "help": "atomic ZBC locked now",
    "kind": "int64",
    "name": "amount",
    "required": true
   },
   {
    "default": "",
    "help": "oracle event id; when set the trigger fires on the event",
    "kind": "string",
    "name": "event_id",
    "required": false
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 15
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "hex",
    "from": "object_id",
    "name": "object_id",
    "size": 32
   }
  ],
  "command": "delete-dataset",
  "custom": null,
  "description": "Delete a dataset object and refund its deposit.",
  "example": {
   "object_id": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "DeleteDataset",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset object id",
    "kind": "hex32",
    "name": "object_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 45
 },
 {
  "binary": "zbc-dfs-create-file",
  "body": [
   {
    "encoding": "str32",
    "from": "path",
    "name": "path"
   },
   {
    "computed": "the file's bytes",
    "encoding": "bytes32",
    "from": "content_file",
    "name": "content"
   }
  ],
  "command": "dfs-create-file",
  "custom": null,
  "description": "Create an on-chain file at path with the given content (up to 64 KB).",
  "example": {
   "content_file": "\u003ca file containing the 12 bytes 'hello zoobc\\n'\u003e",
   "path": "/docs/hello.txt"
  },
  "name": "DFSCreateFile",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "absolute path, e.g. /docs/readme.txt",
    "kind": "string",
    "name": "path",
    "required": true
   },
   {
    "help": "local file whose bytes become the content",
    "kind": "file",
    "name": "content_file",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 8
 },
 {
  "binary": "zbc-escrow-request",
  "body": [
   {
    "encoding": "address",
    "from": "proposed_sender",
    "name": "proposed_sender"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   },
   {
    "encoding": "address",
    "from": "approver",
    "name": "approver"
   },
   {
    "encoding": "u64le",
    "from": "commission",
    "name": "commission"
   },
   {
    "encoding": "u64le",
    "from": "timeout",
    "name": "timeout"
   },
   {
    "encoding": "str32",
    "from": "instruction",
    "name": "instruction"
   },
   {
    "default_from": "timeout",
    "encoding": "u64le",
    "from": "expiry",
    "name": "expiry",
    "when_zero": "timeout"
   }
  ],
  "command": "escrow-request",
  "custom": null,
  "description": "Recipient-initiated escrow: ask proposed_sender to pay amount through an approver.",
  "example": {
   "amount": "250000000",
   "approver": "ZBC_L2HLFDOM_VKKKTEXX_C2P2M6LG_EB6ZNKSV_356SJUWW_5QPVHDE7_EFJA3PEX",
   "commission": "1000",
   "expiry": "0",
   "instruction": "pay on delivery",
   "proposed_sender": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "timeout": "1800000000"
  },
  "name": "EscrowRequest",
  "needs_node": false,
  "notes": [
   "zbc-escrow-request names its first field requester_privkey; zbc-cli uses sender_privkey (ZBC_KEY applies there)."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "who is asked to pay",
    "kind": "address",
    "name": "proposed_sender",
    "required": true
   },
   {
    "help": "proposed amount (atomic units)",
    "kind": "int64",
    "name": "amount",
    "required": true
   },
   {
    "help": "third-party approver",
    "kind": "address",
    "name": "approver",
    "required": true
   },
   {
    "default": "0",
    "help": "approver commission (atomic units)",
    "kind": "int64",
    "name": "commission",
    "required": false
   },
   {
    "help": "escrow timeout, future Unix seconds",
    "kind": "int64",
    "name": "timeout",
    "required": true
   },
   {
    "default": "",
    "help": "instructions",
    "kind": "string",
    "name": "instruction",
    "required": false
   },
   {
    "default": "0",
    "help": "request expiry; 0 = same as timeout",
    "kind": "int64",
    "name": "expiry",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 260
 },
 {
  "binary": "zbc-fee-vote-commit",
  "body": [
   {
    "encoding": "hex",
    "from": "vote_hash",
    "name": "vote_hash",
    "size": 32
   }
  ],
  "command": "fee-vote-commit",
  "custom": null,
  "description": "Commit a hashed fee vote during the commit phase.",
  "example": {
   "vote_hash": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "FeeVoteCommitment",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "32-byte vote hash",
    "kind": "hex32",
    "name": "vote_hash",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 7
 },
 {
  "binary": "zbc-fee-vote-reveal",
  "body": [
   {
    "encoding": "hex",
    "from": "recent_block_hash",
    "name": "recent_block_hash",
    "size": 32
   },
   {
    "encoding": "u32le",
    "from": "recent_block_height",
    "name": "recent_block_height"
   },
   {
    "encoding": "u64le",
    "from": "fee_vote",
    "name": "fee_vote"
   },
   {
    "computed": "u32le length (64) then Ed25519(sender seed, the 44 bytes above), no tag",
    "encoding": "bytes32",
    "from": "voter_signature",
    "name": "voter_signature"
   }
  ],
  "command": "fee-vote-reveal",
  "custom": "voter_signature",
  "description": "Reveal the fee vote during the reveal phase; the body carries the sender's signature over the 44 vote bytes.",
  "example": {
   "fee_vote": "3",
   "recent_block_hash": "1111111111111111111111111111111111111111111111111111111111111111",
   "recent_block_height": "1000"
  },
  "name": "FeeVoteReveal",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "reference block hash",
    "kind": "hex32",
    "name": "recent_block_hash",
    "required": true
   },
   {
    "help": "reference block height",
    "kind": "uint32",
    "name": "recent_block_height",
    "required": true
   },
   {
    "help": "proposed fee multiplier",
    "kind": "int64",
    "name": "fee_vote",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 263
 },
 {
  "binary": "zbc-token-finance",
  "body": [
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id"
   }
  ],
  "command": "finance-token",
  "custom": null,
  "description": "Top up a token's survival financing; the fee buys persistence.",
  "example": {
   "token_id": "123456789"
  },
  "name": "FinanceToken",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "token id",
    "kind": "int64",
    "name": "token_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 14
 },
 {
  "binary": "zbc-fund-longevity",
  "body": [
   {
    "encoding": "u64le",
    "from": "target_tx_id",
    "name": "target_tx_id"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "fund-longevity",
  "custom": null,
  "description": "Attach a rent deposit to a transaction so pruning keeps it.",
  "example": {
   "amount": "10000000",
   "target_tx_id": "-1234567890123456789"
  },
  "name": "FundLongevity",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the transaction to keep, as its int64 id",
    "kind": "int64",
    "name": "target_tx_id",
    "required": true
   },
   {
    "help": "deposit (atomic), minimum 0.1 ZBC",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 52
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "pubkey_of_key",
    "from": "gateway_privkey",
    "name": "gateway_key"
   },
   {
    "encoding": "u32le",
    "from": "reference_height",
    "name": "reference_height"
   },
   {
    "encoding": "hex",
    "from": "reference_block_hash",
    "name": "reference_block_hash",
    "size": 32
   },
   {
    "computed": "Ed25519(gateway seed, the 68 bytes above), no tag",
    "encoding": "hex",
    "from": "signature",
    "name": "signature",
    "size": 64
   }
  ],
  "command": "gateway-heartbeat",
  "custom": "gateway_signature",
  "description": "Liveness proof signed by the gateway key over a recent block; any account may relay it.",
  "example": {
   "gateway_privkey": "2222222222222222222222222222222222222222222222222222222222222222",
   "reference_block_hash": "1111111111111111111111111111111111111111111111111111111111111111",
   "reference_height": "41154"
  },
  "name": "GatewayHeartbeat",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the gateway's own private key",
    "kind": "privkey",
    "name": "gateway_privkey",
    "required": true
   },
   {
    "help": "height of a recent confirmed block",
    "kind": "uint32",
    "name": "reference_height",
    "required": true
   },
   {
    "help": "that block's hash",
    "kind": "hex32",
    "name": "reference_block_hash",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 37
 },
 {
  "binary": "zbc-governance-vote",
  "body": [
   {
    "encoding": "str32",
    "from": "parameter",
    "name": "parameter"
   },
   {
    "encoding": "u64le",
    "from": "value",
    "name": "value"
   }
  ],
  "command": "governance-vote",
  "custom": null,
  "description": "A registry node votes a value for a governable parameter (2/3 of the registry must agree).",
  "example": {
   "parameter": "min_fee",
   "value": "2500000"
  },
  "name": "SetConsensusParam",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand; the node's own key signs."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key (64 hex). Named node_privkey: ZBC_KEY does not apply, pass it explicitly",
    "kind": "privkey",
    "name": "node_privkey",
    "required": true
   },
   {
    "help": "parameter name",
    "kind": "string",
    "name": "parameter",
    "required": true
   },
   {
    "help": "the value voted for, raw units",
    "kind": "int64",
    "name": "value",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "node_privkey",
  "type": 51
 },
 {
  "binary": "zbc-token-issue",
  "body": [
   {
    "encoding": "u8",
    "from": "decimals",
    "name": "decimals"
   },
   {
    "encoding": "u8",
    "from": "flags",
    "name": "flags"
   },
   {
    "encoding": "u64le",
    "from": "supply",
    "name": "supply"
   },
   {
    "encoding": "u64le",
    "from": "backing",
    "name": "backing"
   },
   {
    "encoding": "str16",
    "from": "symbol",
    "name": "symbol"
   },
   {
    "encoding": "str16",
    "from": "name",
    "name": "name"
   }
  ],
  "command": "issue-token",
  "custom": null,
  "description": "Issue a token backed by ZBC.",
  "example": {
   "backing": "100000000",
   "decimals": "2",
   "flags": "1",
   "name": "Gold token",
   "supply": "100000000000",
   "symbol": "GOLD"
  },
  "name": "IssueToken",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "2-10 upper-case letters or digits, not a reserved symbol",
    "kind": "string",
    "name": "symbol",
    "required": true
   },
   {
    "help": "token name",
    "kind": "string",
    "name": "name",
    "required": true
   },
   {
    "help": "0-8, display only",
    "kind": "uint8",
    "max": 8,
    "min": 0,
    "name": "decimals",
    "required": true
   },
   {
    "help": "total supply (atomic, 10^8 per unit)",
    "kind": "int64",
    "name": "supply",
    "required": true
   },
   {
    "help": "ZBC locked as backing (atomic); 0 = unbacked",
    "kind": "int64",
    "name": "backing",
    "required": true
   },
   {
    "default": "1",
    "help": "bit0 redeemable, bit1 mintable, bit3 unbacked",
    "kind": "uint8",
    "name": "flags",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 10
 },
 {
  "binary": "zbc-liquid-stop",
  "body": [
   {
    "encoding": "u64le",
    "from": "transaction_id",
    "name": "transaction_id"
   }
  ],
  "command": "liquid-payment-stop",
  "custom": null,
  "description": "Stop a liquid payment; the vested part goes to the recipient, the rest back.",
  "example": {
   "transaction_id": "-1234567890123456789"
  },
  "name": "LiquidPaymentStop",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the liquid payment's transaction id (first 8 bytes of its hash, int64 LE; often negative)",
    "kind": "int64",
    "name": "transaction_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 262
 },
 {
  "binary": "zbc-liquid-pay",
  "body": [
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   },
   {
    "encoding": "u64le",
    "from": "complete_minutes",
    "name": "complete_minutes"
   },
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id",
    "when": "token_id != 0"
   }
  ],
  "command": "liquid-payment",
  "custom": null,
  "description": "Stream ZBC (or a token) to a recipient, vesting linearly over complete_minutes.",
  "example": {
   "amount": "500000000",
   "complete_minutes": "60",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I"
  },
  "name": "LiquidPayment",
  "needs_node": false,
  "notes": [
   "zbc-cli liquid-payment always streams ZBC; the token_id field comes from zbc-liquid-pay --token \u003cid\u003e."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "recipient address",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "amount (atomic units)",
    "kind": "int64",
    "name": "amount",
    "required": true
   },
   {
    "help": "minutes until fully vested",
    "kind": "uint64",
    "name": "complete_minutes",
    "required": true
   },
   {
    "default": "0",
    "help": "token to stream instead of ZBC (--token); 0 = ZBC",
    "kind": "int64",
    "name": "token_id",
    "required": false
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 6
 },
 {
  "binary": "zbc-market-create",
  "body": [
   {
    "encoding": "u64le",
    "from": "base_token",
    "name": "base_token"
   },
   {
    "encoding": "u64le",
    "from": "quote_token",
    "name": "quote_token"
   },
   {
    "encoding": "u64le",
    "from": "deposit",
    "name": "deposit"
   }
  ],
  "command": "market-create",
  "custom": null,
  "description": "Open a (base, quote) order-book market, paying a rent deposit.",
  "example": {
   "base_token": "123456789",
   "deposit": "100000000",
   "quote_token": "0"
  },
  "name": "CreateMarket",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "base token, 0 = ZBC",
    "kind": "int64",
    "name": "base_token",
    "required": true
   },
   {
    "help": "quote token, 0 = ZBC",
    "kind": "int64",
    "name": "quote_token",
    "required": true
   },
   {
    "default": "0",
    "help": "rent deposit (atomic)",
    "kind": "int64",
    "name": "deposit",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 21
 },
 {
  "binary": "zbc-token-mint",
  "body": [
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "mint-token",
  "custom": null,
  "description": "Mint more of a mintable token (adds backing).",
  "example": {
   "amount": "1000",
   "token_id": "123456789"
  },
  "name": "MintToken",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "token id",
    "kind": "int64",
    "name": "token_id",
    "required": true
   },
   {
    "help": "amount (atomic)",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 12
 },
 {
  "binary": "zbc-multisig",
  "body": [
   {
    "encoding": "literal",
    "from": "info_present",
    "name": "info_present",
    "value": "01000000"
   },
   {
    "encoding": "u32le",
    "from": "min_signatures",
    "name": "min_signatures"
   },
   {
    "encoding": "u64le",
    "from": "nonce",
    "name": "nonce"
   },
   {
    "computed": "number of participants",
    "encoding": "u32le",
    "from": "participants",
    "name": "participant_count"
   },
   {
    "computed": "each 36-byte address, in the order given",
    "encoding": "address_list",
    "from": "participants",
    "name": "participants"
   },
   {
    "computed": "the inner unsigned SendZBC envelope: sender = 36-byte address whose 32-byte key is the multisig address, timestamp = --timestamp or now, fee = inner_fee, body = amount u64le, no escrow, no message",
    "encoding": "bytes32",
    "from": "inner",
    "name": "inner"
   },
   {
    "encoding": "literal",
    "from": "signatures_present",
    "name": "signatures_present",
    "value": "01000000"
   },
   {
    "computed": "SHA3-256(inner) (bare, no tag)",
    "encoding": "hex",
    "from": "inner_hash",
    "name": "inner_hash",
    "size": 32
   },
   {
    "computed": "number of signer keys",
    "encoding": "u32le",
    "from": "signature_count",
    "name": "signature_count"
   },
   {
    "computed": "sorted by the signer's 36-byte address hex: address (36) ‖ u32le 64 ‖ Ed25519(signer seed, signing digest of the inner bytes per signing.md section 4)",
    "encoding": "custom",
    "from": "signatures",
    "name": "signatures"
   }
  ],
  "command": "multisig",
  "custom": "multisig",
  "description": "N-of-M multisig SendZBC: the inner transaction plus the participant signatures gathered so far.",
  "example": {
   "amount": "1000",
   "inner_fee": "10000000",
   "min_signatures": "1",
   "nonce": "0",
   "participants": "ZBC_L2HLFDOM_VKKKTEXX_C2P2M6LG_EB6ZNKSV_356SJUWW_5QPVHDE7_EFJA3PEX,ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "signer_privkeys": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "MultiSignature",
  "needs_node": false,
  "notes": [
   "multisig address = SHA3-256(min_signatures u32le ‖ nonce u64le ‖ count u32le ‖ the participant addresses sorted bytewise).",
   "The multisig account must be funded (send ZBC to its ZBC_ form) before the inner transaction can execute."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "comma-separated participant addresses",
    "kind": "address_list",
    "name": "participants",
    "required": true
   },
   {
    "help": "signatures required (N of M)",
    "kind": "uint32",
    "name": "min_signatures",
    "required": true
   },
   {
    "default": "0",
    "help": "multisig account nonce",
    "kind": "int64",
    "name": "nonce",
    "required": false
   },
   {
    "help": "comma-separated participant keys that sign now",
    "kind": "string",
    "name": "signer_privkeys",
    "required": true
   },
   {
    "help": "inner SendZBC recipient",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "inner amount (atomic)",
    "kind": "int64",
    "name": "amount",
    "required": true
   },
   {
    "default": "10000000",
    "help": "inner fee (atomic)",
    "kind": "int64",
    "name": "inner_fee",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 5
 },
 {
  "binary": "zbc-order-cancel",
  "body": [
   {
    "encoding": "u64le",
    "from": "order_id",
    "name": "order_id"
   }
  ],
  "command": "order-cancel",
  "custom": null,
  "description": "Cancel a resting order; the held remainder is refunded.",
  "example": {
   "order_id": "99"
  },
  "name": "CancelOrder",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "order id",
    "kind": "int64",
    "name": "order_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 23
 },
 {
  "binary": "zbc-order-place",
  "body": [
   {
    "encoding": "u64le",
    "from": "market_id",
    "name": "market_id"
   },
   {
    "encoding": "u8",
    "from": "side",
    "name": "side"
   },
   {
    "encoding": "u64le",
    "from": "price",
    "name": "price"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   },
   {
    "encoding": "u8",
    "from": "flags",
    "name": "flags"
   },
   {
    "encoding": "u64le",
    "from": "expiry",
    "name": "expiry"
   }
  ],
  "command": "order-place",
  "custom": null,
  "description": "Place a limit or market order on a market.",
  "example": {
   "amount": "1000",
   "expiry": "0",
   "flags": "0",
   "market_id": "7",
   "price": "150000000",
   "side": "0"
  },
  "name": "PlaceOrder",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "market id",
    "kind": "int64",
    "name": "market_id",
    "required": true
   },
   {
    "help": "0 = buy, 1 = sell",
    "kind": "uint8",
    "name": "side",
    "required": true
   },
   {
    "help": "quote per base, scaled by 10^8",
    "kind": "int64",
    "name": "price",
    "required": true
   },
   {
    "help": "base amount (atomic)",
    "kind": "int64",
    "name": "amount",
    "required": true
   },
   {
    "default": "0",
    "help": "bit0 market order, bit1 post-only",
    "kind": "uint8",
    "name": "flags",
    "required": false
   },
   {
    "default": "0",
    "help": "Unix seconds, 0 = good till cancelled",
    "kind": "int64",
    "name": "expiry",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 22
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "u64le",
    "from": "schedule_id",
    "name": "schedule_id"
   },
   {
    "encoding": "address",
    "from": "new_recipient",
    "name": "new_recipient"
   }
  ],
  "command": "reassign-schedule",
  "custom": null,
  "description": "Redirect a schedule's future fires to a new recipient.",
  "example": {
   "new_recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "schedule_id": "11"
  },
  "name": "ReassignSchedule",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "schedule id",
    "kind": "int64",
    "name": "schedule_id",
    "required": true
   },
   {
    "help": "new recipient",
    "kind": "address",
    "name": "new_recipient",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 31
 },
 {
  "binary": "zbc-gateway-register",
  "body": [
   {
    "encoding": "key32",
    "from": "gateway_key",
    "name": "gateway_key"
   },
   {
    "encoding": "str32",
    "from": "domain",
    "name": "domain"
   },
   {
    "encoding": "str32",
    "from": "url",
    "name": "url"
   }
  ],
  "command": "register-gateway",
  "custom": null,
  "description": "Announce a gateway you run, locking the registration stake.",
  "example": {
   "domain": "gw.example.org",
   "gateway_key": "2222222222222222222222222222222222222222222222222222222222222222",
   "url": "https://gw.example.org"
  },
  "name": "RegisterGateway",
  "needs_node": false,
  "notes": [
   "zbc-gateway-register names its first field owner_privkey."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "gateway public key: 64 hex (zbc-cli) or ZBG_ address (zbc-gateway-register)",
    "kind": "key",
    "name": "gateway_key",
    "required": true
   },
   {
    "help": "public domain, 1-256 chars",
    "kind": "string",
    "name": "domain",
    "required": true
   },
   {
    "help": "base URL",
    "kind": "string",
    "name": "url",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 36
 },
 {
  "binary": "zbc-node-register",
  "body": [
   {
    "encoding": "pubkey_of_key",
    "from": "node_privkey",
    "name": "node_public_key"
   },
   {
    "computed": "the owner's 36-byte account",
    "encoding": "sender_address",
    "from": "owner",
    "name": "owner"
   },
   {
    "encoding": "u64le",
    "from": "locked_balance",
    "name": "locked_balance"
   },
   {
    "computed": "136 bytes: owner address (36) ‖ latest block hash (32) ‖ latest block height u32le ‖ Ed25519(owner seed, those 72 bytes); block from GET /api/v1/blocks/latest",
    "encoding": "custom",
    "from": "proof_of_ownership",
    "name": "proof_of_ownership"
   }
  ],
  "command": "register-node",
  "custom": "proof_of_ownership",
  "description": "Register a node with a locked stake; the owner proves control of the node key.",
  "example": {
   "locked_balance": "100000000000",
   "node_privkey": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "NodeRegistration",
  "needs_node": true,
  "notes": [
   "zbc-node-register takes (node_privkey, owner_privkey, locked_balance): node key first, then the owner key that signs."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the node's private key; its public key goes in the body",
    "kind": "privkey",
    "name": "node_privkey",
    "required": true
   },
   {
    "help": "stake to lock (atomic)",
    "kind": "int64",
    "name": "locked_balance",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 2
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "str32",
    "from": "version",
    "name": "version"
   },
   {
    "encoding": "hex",
    "from": "manifest_hash",
    "name": "manifest_hash",
    "size": 32
   },
   {
    "encoding": "address",
    "from": "release_address",
    "name": "release_address"
   }
  ],
  "command": "register-release",
  "custom": null,
  "description": "Publish a signed binary release (release authority only).",
  "example": {
   "manifest_hash": "1111111111111111111111111111111111111111111111111111111111111111",
   "release_address": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "version": "0.4.2"
  },
  "name": "RegisterRelease",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "release version, 1-256 chars",
    "kind": "string",
    "name": "version",
    "required": true
   },
   {
    "help": "manifest hash",
    "kind": "hex32",
    "name": "manifest_hash",
    "required": true
   },
   {
    "help": "the release's on-chain address",
    "kind": "address",
    "name": "release_address",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 32
 },
 {
  "binary": "zbc-relay-register",
  "body": [
   {
    "encoding": "key32",
    "from": "relay_key",
    "name": "relay_key"
   },
   {
    "encoding": "key32",
    "from": "gateway_key",
    "name": "gateway_key"
   },
   {
    "encoding": "str32",
    "from": "domain",
    "name": "domain"
   },
   {
    "encoding": "str32",
    "from": "url",
    "name": "url"
   }
  ],
  "command": "relay-register",
  "custom": null,
  "description": "Announce a relay a gateway runs.",
  "example": {
   "domain": "relay.example.org",
   "gateway_key": "2222222222222222222222222222222222222222222222222222222222222222",
   "relay_key": "1111111111111111111111111111111111111111111111111111111111111111",
   "url": "https://relay.example.org"
  },
  "name": "RegisterRelay",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key (64 hex). Named owner_privkey: ZBC_KEY does not apply, pass it explicitly",
    "kind": "privkey",
    "name": "owner_privkey",
    "required": true
   },
   {
    "help": "the relay's ZBR_ address or 64 hex",
    "kind": "key",
    "name": "relay_key",
    "required": true
   },
   {
    "help": "the ZBG_ address or 64 hex of the gateway it serves",
    "kind": "key",
    "name": "gateway_key",
    "required": true
   },
   {
    "help": "public domain",
    "kind": "string",
    "name": "domain",
    "required": true
   },
   {
    "help": "base URL",
    "kind": "string",
    "name": "url",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "owner_privkey",
  "type": 48
 },
 {
  "binary": "zbc-relay-unregister",
  "body": [
   {
    "encoding": "key32",
    "from": "relay_key",
    "name": "relay_key"
   }
  ],
  "command": "relay-unregister",
  "custom": null,
  "description": "Withdraw a relay announcement.",
  "example": {
   "relay_key": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "UnregisterRelay",
  "needs_node": false,
  "notes": [
   "No zbc-cli subcommand."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key (64 hex). Named owner_privkey: ZBC_KEY does not apply, pass it explicitly",
    "kind": "privkey",
    "name": "owner_privkey",
    "required": true
   },
   {
    "help": "the relay's ZBR_ address or 64 hex",
    "kind": "key",
    "name": "relay_key",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "owner_privkey",
  "type": 49
 },
 {
  "binary": null,
  "body": [],
  "command": "release-authority-accept",
  "custom": null,
  "description": "Accept a pending release-authority handover. Empty body.",
  "example": {},
  "name": "ReleaseAuthorityAccept",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 34
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "address",
    "from": "new_authority",
    "name": "new_authority"
   }
  ],
  "command": "release-authority-propose",
  "custom": null,
  "description": "Propose handing the release authority to another account.",
  "example": {
   "new_authority": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I"
  },
  "name": "ReleaseAuthorityPropose",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "proposed new authority",
    "kind": "address",
    "name": "new_authority",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 33
 },
 {
  "binary": "zbc-dataset-remove",
  "body": [
   {
    "encoding": "str32",
    "from": "property",
    "name": "property"
   },
   {
    "encoding": "str32",
    "from": "value",
    "name": "value"
   },
   {
    "computed": "the sender's 36-byte account",
    "encoding": "sender_address",
    "from": "setter",
    "name": "setter"
   },
   {
    "encoding": "address",
    "from": "recipient",
    "name": "recipient"
   }
  ],
  "command": "remove-dataset",
  "custom": null,
  "description": "Deactivate a key-value property; same body layout as setup-dataset.",
  "example": {
   "property": "role",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "value": "tester"
  },
  "name": "RemoveAccountDataset",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset subject address",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "key",
    "kind": "string",
    "name": "property",
    "required": true
   },
   {
    "help": "value",
    "kind": "string",
    "name": "value",
    "required": true
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 259
 },
 {
  "binary": "zbc-node-remove",
  "body": [
   {
    "encoding": "pubkey_of_key",
    "from": "node_privkey",
    "name": "node_public_key"
   }
  ],
  "command": "remove-node",
  "custom": null,
  "description": "Remove a node from the registry; the locked balance returns to the owner.",
  "example": {
   "node_privkey": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "RemoveNodeRegistration",
  "needs_node": false,
  "notes": [
   "zbc-node-remove takes (node_privkey, owner_privkey)."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the node's private key; its public key is the body",
    "kind": "privkey",
    "name": "node_privkey",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 514
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "str32",
    "from": "version",
    "name": "version"
   }
  ],
  "command": "revoke-release",
  "custom": null,
  "description": "Revoke a published release.",
  "example": {
   "version": "0.4.2"
  },
  "name": "RevokeRelease",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "version to revoke",
    "kind": "string",
    "name": "version",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 35
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id"
   },
   {
    "encoding": "u64le",
    "from": "per_fire_amount",
    "name": "per_fire_amount"
   },
   {
    "encoding": "u64le",
    "from": "interval_seconds",
    "name": "interval_seconds"
   },
   {
    "encoding": "u32le",
    "from": "remaining_fires",
    "name": "remaining_fires"
   },
   {
    "encoding": "u64le",
    "from": "cliff_seconds",
    "name": "cliff_seconds"
   },
   {
    "encoding": "u8",
    "from": "funding_mode",
    "name": "funding_mode"
   },
   {
    "encoding": "u8",
    "from": "cancel_policy",
    "name": "cancel_policy"
   },
   {
    "encoding": "u64le",
    "from": "end_time",
    "name": "end_time"
   },
   {
    "encoding": "literal",
    "from": "reserved",
    "name": "reserved",
    "value": "00"
   }
  ],
  "command": "scheduled-transfer",
  "custom": null,
  "description": "Recurring or vested transfers to a recipient.",
  "example": {
   "cancel_policy": "0",
   "cliff_seconds": "0",
   "end_time": "0",
   "funding_mode": "0",
   "interval_seconds": "86400",
   "per_fire_amount": "100000000",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "remaining_fires": "3",
   "token_id": "0"
  },
  "name": "ScheduledTransfer",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "paid on each fire",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "default": "0",
    "help": "0 = ZBC",
    "kind": "int64",
    "name": "token_id",
    "required": false
   },
   {
    "help": "amount per fire (atomic), \u003e 0",
    "kind": "int64",
    "name": "per_fire_amount",
    "required": true
   },
   {
    "default": "0",
    "help": "seconds between fires",
    "kind": "int64",
    "name": "interval_seconds",
    "required": false
   },
   {
    "help": "number of fires, \u003e= 1",
    "kind": "uint32",
    "name": "remaining_fires",
    "required": true
   },
   {
    "default": "0",
    "help": "delay before the first fire",
    "kind": "int64",
    "name": "cliff_seconds",
    "required": false
   },
   {
    "default": "0",
    "help": "0 pre-lock now, 1 pull at fire",
    "kind": "uint8",
    "name": "funding_mode",
    "required": false
   },
   {
    "default": "0",
    "help": "0 or 1",
    "kind": "uint8",
    "name": "cancel_policy",
    "required": false
   },
   {
    "default": "0",
    "help": "Unix-seconds cutoff, 0 = none",
    "kind": "int64",
    "name": "end_time",
    "required": false
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 29
 },
 {
  "binary": "zbc-send",
  "body": [
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "send-zbc",
  "custom": null,
  "description": "Send ZBC from the sender to a recipient; optionally escrowed.",
  "example": {
   "amount": "100000000",
   "recipient": "ZBC_L2HLFDOM_VKKKTEXX_C2P2M6LG_EB6ZNKSV_356SJUWW_5QPVHDE7_EFJA3PEX"
  },
  "name": "SendZBC",
  "needs_node": false,
  "notes": [
   "zbc-send also accepts --liquid \u003cminutes\u003e, which makes it a LiquidPayment (type 6) instead."
  ],
  "options": [
   "message",
   "encrypt",
   "escrow",
   "chain"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "recipient address (ZBC_, 64 hex, or another chain's address)",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "amount in atomic units (1 ZBC = 100000000)",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 1
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "hex",
    "from": "object_id",
    "name": "object_id",
    "size": 32
   },
   {
    "encoding": "u8",
    "from": "mode",
    "name": "mode"
   },
   {
    "encoding": "address_list8",
    "from": "add",
    "name": "add"
   },
   {
    "encoding": "address_list8",
    "from": "remove",
    "name": "remove"
   }
  ],
  "command": "set-dataset-policy",
  "custom": null,
  "description": "Set a dataset object's manage policy and edit its access lists.",
  "example": {
   "add": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "mode": "1",
   "object_id": "1111111111111111111111111111111111111111111111111111111111111111",
   "remove": ""
  },
  "name": "SetDatasetPolicy",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset object id",
    "kind": "hex32",
    "name": "object_id",
    "required": true
   },
   {
    "help": "0 owner-only, 1 whitelist, 2 blacklist, 3 open",
    "kind": "uint8",
    "max": 3,
    "min": 0,
    "name": "mode",
    "required": true
   },
   {
    "default": "",
    "help": "comma-separated addresses to add (max 255)",
    "kind": "address_list",
    "name": "add",
    "required": false
   },
   {
    "default": "",
    "help": "comma-separated addresses to remove (max 255)",
    "kind": "address_list",
    "name": "remove",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 43
 },
 {
  "binary": "zbc-dataset-setup",
  "body": [
   {
    "encoding": "str32",
    "from": "property",
    "name": "property"
   },
   {
    "encoding": "str32",
    "from": "value",
    "name": "value"
   },
   {
    "computed": "the sender's 36-byte account",
    "encoding": "sender_address",
    "from": "setter",
    "name": "setter"
   },
   {
    "encoding": "address",
    "from": "recipient",
    "name": "recipient"
   }
  ],
  "command": "setup-dataset",
  "custom": null,
  "description": "Set a key-value property on an account (the recipient is the subject).",
  "example": {
   "property": "role",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "value": "tester"
  },
  "name": "SetupAccountDataset",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset subject address",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "key",
    "kind": "string",
    "name": "property",
    "required": true
   },
   {
    "help": "value",
    "kind": "string",
    "name": "value",
    "required": true
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 3
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "hex",
    "from": "file_root",
    "name": "file_root",
    "size": 32
   },
   {
    "encoding": "u64le",
    "from": "total_size",
    "name": "total_size"
   },
   {
    "encoding": "u32le",
    "from": "piece_size",
    "name": "piece_size"
   },
   {
    "encoding": "u64le",
    "from": "deposit",
    "name": "deposit"
   },
   {
    "computed": "len(piece_ids) / 32",
    "encoding": "u32le",
    "from": "piece_ids",
    "name": "piece_count"
   },
   {
    "encoding": "hex",
    "from": "piece_ids",
    "name": "piece_ids"
   }
  ],
  "command": "store-file",
  "custom": null,
  "description": "Anchor a decentralised-storage manifest (root and piece ids) with a rent deposit.",
  "example": {
   "deposit": "100000000",
   "file_root": "1111111111111111111111111111111111111111111111111111111111111111",
   "piece_ids": "11111111111111111111111111111111111111111111111111111111111111112222222222222222222222222222222222222222222222222222222222222222",
   "piece_size": "2048",
   "total_size": "4096"
  },
  "name": "StoreFile",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "manifest root hash",
    "kind": "hex32",
    "name": "file_root",
    "required": true
   },
   {
    "help": "file size in bytes",
    "kind": "int64",
    "name": "total_size",
    "required": true
   },
   {
    "help": "piece size in bytes",
    "kind": "uint32",
    "name": "piece_size",
    "required": true
   },
   {
    "help": "rent deposit (atomic)",
    "kind": "int64",
    "name": "deposit",
    "required": true
   },
   {
    "help": "piece id hashes concatenated, n x 32 bytes",
    "kind": "hexbytes",
    "name": "piece_ids",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 40
 },
 {
  "binary": "zbc-swap-accept",
  "body": [
   {
    "encoding": "u64le",
    "from": "offer_id",
    "name": "offer_id"
   }
  ],
  "command": "swap-accept",
  "custom": null,
  "description": "Fill an open swap offer.",
  "example": {
   "offer_id": "42"
  },
  "name": "AcceptSwapOffer",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "offer id",
    "kind": "int64",
    "name": "offer_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 19
 },
 {
  "binary": "zbc-swap-cancel",
  "body": [
   {
    "encoding": "u64le",
    "from": "offer_id",
    "name": "offer_id"
   }
  ],
  "command": "swap-cancel",
  "custom": null,
  "description": "Cancel your open swap offer; the held amount is refunded.",
  "example": {
   "offer_id": "42"
  },
  "name": "CancelSwapOffer",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "offer id",
    "kind": "int64",
    "name": "offer_id",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 20
 },
 {
  "binary": "zbc-swap-create",
  "body": [
   {
    "encoding": "u64le",
    "from": "give_token",
    "name": "give_token"
   },
   {
    "encoding": "u64le",
    "from": "give_amount",
    "name": "give_amount"
   },
   {
    "encoding": "u64le",
    "from": "want_token",
    "name": "want_token"
   },
   {
    "encoding": "u64le",
    "from": "want_amount",
    "name": "want_amount"
   },
   {
    "encoding": "u64le",
    "from": "expiry",
    "name": "expiry"
   }
  ],
  "command": "swap-create",
  "custom": null,
  "description": "Offer give_amount of give_token for want_amount of want_token; the give side is held.",
  "example": {
   "expiry": "0",
   "give_amount": "100000000",
   "give_token": "0",
   "want_amount": "5000",
   "want_token": "123456789"
  },
  "name": "CreateSwapOffer",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "token to give, 0 = ZBC",
    "kind": "int64",
    "name": "give_token",
    "required": true
   },
   {
    "help": "atomic",
    "kind": "int64",
    "name": "give_amount",
    "required": true
   },
   {
    "help": "token wanted, 0 = ZBC",
    "kind": "int64",
    "name": "want_token",
    "required": true
   },
   {
    "help": "atomic",
    "kind": "int64",
    "name": "want_amount",
    "required": true
   },
   {
    "default": "0",
    "help": "Unix seconds, 0 = good till cancelled",
    "kind": "int64",
    "name": "expiry",
    "required": false
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 18
 },
 {
  "binary": null,
  "body": [
   {
    "encoding": "hex",
    "from": "object_id",
    "name": "object_id",
    "size": 32
   },
   {
    "encoding": "address",
    "from": "new_owner",
    "name": "new_owner"
   }
  ],
  "command": "transfer-dataset",
  "custom": null,
  "description": "Propose transferring a dataset object to a new owner.",
  "example": {
   "new_owner": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "object_id": "1111111111111111111111111111111111111111111111111111111111111111"
  },
  "name": "TransferDataset",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "dataset object id = the creating transaction hash",
    "kind": "hex32",
    "name": "object_id",
    "required": true
   },
   {
    "help": "new owner",
    "kind": "address",
    "name": "new_owner",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 42
 },
 {
  "binary": "zbc-token-transfer",
  "body": [
   {
    "encoding": "u64le",
    "from": "token_id",
    "name": "token_id"
   },
   {
    "encoding": "u64le",
    "from": "amount",
    "name": "amount"
   }
  ],
  "command": "transfer-token",
  "custom": null,
  "description": "Transfer a token to a recipient.",
  "example": {
   "amount": "500",
   "recipient": "ZBC_2BFLEMTU_FO2KWOQT_NC6UMFPE_43ICESVX_DIAWXL4F_ECRTFSLX_Q43UIV2I",
   "token_id": "-4611686018427387904"
  },
  "name": "TransferToken",
  "needs_node": false,
  "notes": [],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "recipient address",
    "kind": "address",
    "name": "recipient",
    "required": true
   },
   {
    "help": "token id",
    "kind": "int64",
    "name": "token_id",
    "required": true
   },
   {
    "help": "amount (atomic), \u003e 0",
    "kind": "int64",
    "name": "amount",
    "required": true
   }
  ],
  "recipient": "required",
  "sender_key": "sender_privkey",
  "type": 11
 },
 {
  "binary": "zbc-gateway-unregister",
  "body": [
   {
    "encoding": "key32",
    "from": "gateway_key",
    "name": "gateway_key"
   }
  ],
  "command": "unregister-gateway",
  "custom": null,
  "description": "Withdraw a gateway you registered; the stake is refunded.",
  "example": {
   "gateway_key": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "UnregisterGateway",
  "needs_node": false,
  "notes": [
   "zbc-gateway-unregister names its first field owner_privkey."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "gateway public key",
    "kind": "key",
    "name": "gateway_key",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 38
 },
 {
  "binary": "zbc-node-update",
  "body": [
   {
    "encoding": "pubkey_of_key",
    "from": "node_privkey",
    "name": "node_public_key"
   },
   {
    "encoding": "u64le",
    "from": "locked_balance",
    "name": "locked_balance"
   },
   {
    "computed": "as register-node",
    "encoding": "custom",
    "from": "proof_of_ownership",
    "name": "proof_of_ownership"
   }
  ],
  "command": "update-node",
  "custom": "proof_of_ownership",
  "description": "Change a node registration's locked balance.",
  "example": {
   "locked_balance": "200000000000",
   "node_privkey": "2222222222222222222222222222222222222222222222222222222222222222"
  },
  "name": "NodeRegistrationUpdate",
  "needs_node": true,
  "notes": [
   "zbc-node-update takes (node_privkey, owner_privkey, new_locked_balance)."
  ],
  "options": [
   "message",
   "encrypt"
  ],
  "params": [
   {
    "help": "the signing key: 32-byte Ed25519 seed as 64 hex; '-' or omitted = ZBC_KEY",
    "kind": "privkey",
    "name": "sender_privkey",
    "required": true
   },
   {
    "help": "the node's private key",
    "kind": "privkey",
    "name": "node_privkey",
    "required": true
   },
   {
    "help": "new stake (atomic)",
    "kind": "int64",
    "name": "locked_balance",
    "required": true
   }
  ],
  "recipient": "none",
  "sender_key": "sender_privkey",
  "type": 258
 }
]`
