#!/usr/bin/env perl
# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci
# Embed spec/transactions/*.json into lib/ZBC/Commands.pm so the distribution carries its own command table.
# Run from perl/: perl script/gen-commands.pl   (CI checks the result is current)
use strict; use warnings;
use FindBin;
use JSON::PP;

my $spec = "$FindBin::Bin/../../spec/transactions";
my $json = JSON::PP->new->utf8->canonical->pretty->indent_length(1);
my @defs;
for my $file (sort glob "$spec/*.json") {
    next if $file =~ /index\.json$/;
    open my $fh, '<:raw', $file or die "$file: $!";
    my $d = $json->decode(do { local $/; <$fh> });
    delete $d->{license};
    push @defs, $d;
}
my $text = JSON::PP->new->ascii->canonical->pretty->indent_length(1)->encode(\@defs);
my $out = "$FindBin::Bin/../lib/ZBC/Commands.pm";
open my $fh, '>:raw', $out or die "$out: $!";
print $fh <<"HEAD" . $text . <<'TAIL';
# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci
# GENERATED by script/gen-commands.pl from spec/transactions/*.json. Do not edit.
package ZBC::Commands;
# The command table: one entry per transaction type, in the schema of spec/transactions/README.md.
use strict; use warnings;
use JSON::PP ();

our \$JSON = <<'END_OF_SPEC';
HEAD
END_OF_SPEC

our @COMMANDS = @{ JSON::PP->new->decode($JSON) };
our %COMMAND_BY_NAME = map { $_->{command} => $_ } @COMMANDS;

# The entry of a command name, or undef.
sub by_name { my ($name) = @_; return $COMMAND_BY_NAME{$name}; }
# Every entry, in file order (sorted by file name).
sub all { return @COMMANDS; }

1;
TAIL
close $fh;
printf "generated %d commands into %s\n", scalar @defs, $out;
