// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci

// GENERATED by internal/gen: the dfs-create-file command as its own program.

package main

import (
	"os"

	"github.com/zoobc/tools/go/cli"
)

func main() { os.Exit(cli.RunTool("dfs-create-file", os.Args[1:], os.Stdin, os.Stdout, os.Stderr)) }
