#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci
"""Embed spec/transactions/*.json into zbc/_commands.py so the package carries its own command table.
Run from py/: python3 scripts/gen_commands.py   (CI checks the result is current)."""
import json
import pathlib

here = pathlib.Path(__file__).resolve().parent
spec = here.parent.parent / "spec" / "transactions"
defs = []
for f in sorted(spec.glob("*.json")):
    if f.name == "index.json":
        continue
    d = json.loads(f.read_text())
    d.pop("license", None)
    defs.append(d)
out = ["# SPDX-License-Identifier: MIT", "# Copyright (c) 2024-2026 ZooBC Foundation and Roberto Capodieci",
       "# GENERATED by scripts/gen_commands.py from spec/transactions/*.json. Do not edit.", "",
       "COMMANDS = " + json.dumps(defs, indent=1, ensure_ascii=False).replace(": true", ": True").replace(": false", ": False").replace(": null", ": None"),
       "", "COMMAND_BY_NAME = {c[\"command\"]: c for c in COMMANDS}", ""]
(here.parent / "zbc" / "_commands.py").write_text("\n".join(out))
print("generated %d commands" % len(defs))
